spring:
  application:
    name: hello-spring-cloud-admin
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8580
  hostname: localhost

management:
  endpoint:
    health:
      show-detail: always
  endpoints:
    web:
      exposure:
        include: ["health", "info"]

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/