spring:
  application:
    name: hello-spring-cloud-config
  boot:
    admin:
      client:
        url: http://localhost:8580
  cloud:
    config:
      label: main
      server:
        git:
          uri: https://github.com/XIXIAOSHI124/hello-spring-cloud-configuration.git
            search-paths: configurations
            username: XIXIAOSHI124
            password: Vin900726
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8888
  hostname: localhost

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/