spring:
  application:
    name: hello-spring-cloud-zipkin
  main:
    allow-bean-definition-overriding: true

server:
  port: 9411
  hostname: localhost

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false