spring:
  application:
    name: hello-spring-cloud-service-admin
  boot:
    admin:
      client:
        url: http://localhost:8580
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8181
  hostname: localhost

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/