spring:
  application:
    name: hello-spring-cloud-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8580

server:
  port: 9411
  hostname: localhost

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false